version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - dep-{{ checksum "composer.json" }}
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ./bin
            - ./vendor
          key: dep-{{ checksum "composer.json" }}
executors:
  docker-executor:
    docker:
      - image: circleci/php:7.2-fpm-node-browsers
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD

jobs:
  build:
    executor: docker-executor
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache_cmd
      - run: make ci-install
      - save_cache_cmd
  test:
    executor: docker-executor
    working_directory: ~/repo
    steps:
      - checkout
      - run: make ci-setup-code-climate
      - restore_cache_cmd
      - run: make ci-test

workflows:
  version: 2
  on_push:
    jobs:
      - build:
        filters:
          branches:
            only:
              - develop
              - master
              - ^(?>features|fixes)\/{1}[[:alnum:]]+$
      - test:
          requires:
            - build
