version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-fpm-node-browsers
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: make ci-install
      - run: make ci-setup-code-climate
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: make ci-test
workflows:
  version: 2
  on_push:
    jobs:
      - build
