name: build, test, build for prod, packages and deploy

on:
  push:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      BUILD_IMG: docker://michelmaier/docker-build-php:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache vendors
        uses: actions/cache@v2
        with:
          path: vendor
          key: build-cache-vendors-${{ hashFiles('composer.json') }}
      - name: Install vendors
        uses: docker://michelmaier/docker-build-php:latest
        with:
          args: make ci-install
      - name: Setup code climate
        uses: docker://michelmaier/docker-build-php:latest
        with:
          args: make ci-setup-code-climate
      - name: Tests and publish report
        uses: docker://michelmaier/docker-build-php:latest
        with:
          args: make ci-test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: reports/
          retention-days: 5
  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache vendors
        uses: actions/cache@v2
        with:
          path: vendor
          key: build-cache-vendors-prod-${{ hashFiles('composer.json') }}
      - name: Build for production
        uses: docker://michelmaier/docker-build-php:latest
        with:
          args: make ci-install-prod
      - name: package
        uses: docker://michelmaier/docker-build-php:latest
        with:
          args: make ci-package
  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - shell: bash
        run: |
          echo "deploy"